name: Build Windows

on:
  push:
    branches: [ "windows-fix" ]
  pull_request:
    branches: [ "windows-fix" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      CCACHE_DIR: ${{ github.workspace }}\.ccache

    steps:
    - uses: actions/checkout@v5

    - name: Clone mlib submodule
      run: |
        git submodule update --init --depth 1 --single-branch util/mlib

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ucrt64
        pacboy: >-
          git:
          glib2:p
          gcc:p
          dtc:p
          pixman:p
          zlib:p
          libtasn1:p
          ninja:p
          meson:p
          base-devel:
          cmake:
          gnutls:p
          pkgconf:p
          SDL2:p
          libssh:p
          gtk3:p
          nsis:p
          ccache:p

    - name: Prepare ccache directory
      shell: msys2 {0}
      run: |
        mkdir -p "$(cygpath -u "$CCACHE_DIR")"
        ccache -p

    - name: Cache ccache
      uses: actions/cache@v5
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ${{ runner.os }}-ccache-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-ccache-

    - name: Reset ccache stats
      shell: msys2 {0}
      run: |
        ccache -z

    - name: Build and Install with Make
      shell: msys2 {0}
      run: |
        git clone https://github.com/lzfse/lzfse.git && cd lzfse
        make -j$(nproc)
        cp build/bin/lzfse $MSYSTEM_PREFIX/bin/
        cp build/bin/liblzfse.a $MSYSTEM_PREFIX/lib/
        cp src/lzfse.h $MSYSTEM_PREFIX/include/
        
    - name: Configure
      shell: msys2 {0}
      run: |
        mkdir build && cd build
        ../configure --target-list=aarch64-softmmu,x86_64-softmmu --enable-lzfse --enable-slirp --enable-curses --enable-libssh --disable-virtfs --enable-zstd --enable-nettle --enable-gnutls --enable-gtk --enable-sdl --disable-werror --disable-qom-cast-debug --extra-cflags="-O3 -ffast-math -march=x86-64-v3" --disable-debug-info --cc="ccache gcc" --cxx="ccache g++"

    - name: Build
      shell: msys2 {0}
      run: |
        cd build
        make -j$(nproc)

    - name: Show ccache stats
      shell: msys2 {0}
      run: |
        ccache -sv
        du -sh "$(cygpath -u "$CCACHE_DIR")"

    - name: Make NSIS Installer
      shell: msys2 {0}
      run: |
        cd build
        make installer

    - name: Upload Artifact
      uses: actions/upload-artifact@v6
      with:
        name: windows-installer
        path: build/qemu-setup-*.exe
